weights: yolov7.pt
cfg: cfg/training/yolov7.yaml
data: data/custom.yaml
hyp: data/hyp.scratch.p5.yaml
epochs: 5
batch_size: 1
img_size:
- 1216
- 800
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 2
project: runs/train
entity: null
name: yolov7
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze:
- 0
world_size: 1
global_rank: -1
save_dir: runs/train/yolov725
total_batch_size: 1
